iot:
  target_mode: ged
  normalize_target: true
  gnn_operator: gin
  filters_1: 128
  filters_2: 64
  filters_3: 32
  tensor_neurons: 16
  bottle_neck_neurons: 16
  bottle_neck_neurons_2: 8
  bottle_neck_neurons_3: 4
  dropout: 0.5
  value_loss: mse
  value_loss_weight: 8.0
  matching_loss: bce
  matching_loss_weight: 2.0
  sinkhorn_iters: 5
  sinkhorn_eps: 0.05
  gedgw_alpha: 0.3333333333333333
  gedgw_outer_iters: 20
  gedgw_sinkhorn_iters: 30
  gedgw_sinkhorn_eps: 0.1

gw:
  target_mode: ged
  normalize_target: false
  gnn_operator: gin
  filters_1: 128
  filters_2: 64
  filters_3: 32
  tensor_neurons: 16
  bottle_neck_neurons: 16
  bottle_neck_neurons_2: 8
  bottle_neck_neurons_3: 4
  dropout: 0.5
  value_loss: mse
  value_loss_weight: 1.0
  matching_loss: bce
  matching_loss_weight: 1.0
  sinkhorn_iters: 5
  sinkhorn_eps: 0.05
  gedgw_alpha: 0.3333333333333333
  gedgw_outer_iters: 20
  gedgw_sinkhorn_iters: 30
  gedgw_sinkhorn_eps: 0.1

hot:
  target_mode: ged
  normalize_target: true
  gnn_operator: gin
  filters_1: 128
  filters_2: 64
  filters_3: 32
  tensor_neurons: 16
  bottle_neck_neurons: 16
  bottle_neck_neurons_2: 8
  bottle_neck_neurons_3: 4
  dropout: 0.5
  value_loss: mse
  value_loss_weight: 8.0
  matching_loss: bce
  matching_loss_weight: 2.0
  sinkhorn_iters: 5
  sinkhorn_eps: 0.05
  gedgw_alpha: 0.3333333333333333
  gedgw_outer_iters: 20
  gedgw_sinkhorn_iters: 30
  gedgw_sinkhorn_eps: 0.1
