target_mode: ged
normalize_target: true
aux_target_mode: null
aux_normalize_target: false
num_layers: 8
hidden_dim: 64
output_dim: 32
layer_type: GIN
skip_connection: identity
dropout: 0.0
alpha_type: learnable
num_perms: 5
length_pe: 3
max_num_nodes: 90
norm: layer
act: ReLU
score_rep: true
target_eps: 1.0e-8
value_loss: mse
value_loss_weight: 1.0
aux_value_loss: mse
aux_value_loss_weight: 1.0
multi_task_loss: none
