dataset_name: AIDS700nef
target_mode: ged
normalize_target: true
gnn_operator: gcn
filters_1: 64
filters_2: 32
filters_3: 16
tensor_neurons: 16
bins: 16
bottle_neck_neurons: 16
dropout: 0.0
histogram: false
diffpool: false
astar_beamwidth: 0
astar_trustfact: 1.0
astar_nopred: 0
astar_use_net: true
enable_astar_finetune: false
astar_finetune_max_states: 0
