target_mode: ged
normalize_target: false
variant: match
node_state_dim: 32
edge_state_dim: 16
graph_rep_dim: 128
encoder:
  node_hidden_sizes:
    - 32
  node_feature_dim: 1
  edge_hidden_sizes:
    - 16
aggregator:
  node_hidden_sizes:
    - 128
  graph_transform_sizes:
    - 128
  input_size:
    - 32
  gated: true
  aggregation_type: sum
graph_embedding_net:
  node_state_dim: 32
  edge_state_dim: 16
  edge_hidden_sizes:
    - 64
    - 64
  node_hidden_sizes:
    - 64
  n_prop_layers: 5
  share_prop_params: true
  edge_net_init_scale: 0.1
  node_update_type: gru
  use_reverse_direction: true
  reverse_dir_param_different: false
  layer_norm: false
  prop_type: embedding
graph_matching_net:
  node_state_dim: 32
  edge_state_dim: 16
  edge_hidden_sizes:
    - 64
    - 64
  node_hidden_sizes:
    - 64
  n_prop_layers: 5
  share_prop_params: true
  edge_net_init_scale: 0.1
  node_update_type: gru
  use_reverse_direction: true
  reverse_dir_param_different: false
  layer_norm: false
  similarity: dotproduct
  prop_type: matching
